:- module(facts,[]).
place(phra_nakhon_khiri_historical_park).
place(khao_luang_cave).
place(wat_khoi_temple).
place(wat_yai_suwannaram_temple).
place(saiyat_buddhist_temple).
place(mahathat_worawihan_temple).
place(kamphaeng_laeng_temple).
place(khao_bandai_it_temple).
place(phra_ram_ratchaniwet).
place(chaosamran_beach).
place(cha_am_beach).
place(maruekhathaiyawan_palace).
place(cha_am_forest_park).
place(khao_nang_panthurat_forest_park).
place(the_sirindhorn_international_environmental_park).
place(somdet_phra_srinagarindra_park).
place(neranchararam_temple).
place(dok_krachiao_field).
place(cha_am_khiri_temple).
place(hoob_krapong_learning_center).
place(huai_sai_education_development_center).
place(thung_faek_valley).
place(chao_por_khao_yai_shrine).
place(tha_sai_island).
place(na_yang_bat_cave).
place(khao_ta_chin_cave).
place(hup_sabu_waterfall).
place(cha_am_atv_park).
place(santorini_park).
place(swiss_sheep_farm).
place(camel_republic).
place(the_venezia_huahin).
place(kaeng_krachan_national_park).
place(khao_yoi_cave).
place(tai_dam_cultural_village).
place(ban_laem_salt_pan).
place(bang_tabun_bay).
place(khao_takrao_temple).
place(laem_luang_beach).
place(bang_khun_sai_village).
place(puek_tian_beach).
place(nong_ya_plong_hot_springs).
has_place(meuang,phra_nakhon_khiri_historical_park).
has_place(meuang,khao_luang_cave).
has_place(meuang,wat_khoi_temple).
has_place(meuang,wat_yai_suwannaram_temple).
has_place(meuang,saiyat_buddhist_temple).
has_place(meuang,mahathat_worawihan_temple).
has_place(meuang,kamphaeng_laeng_temple).
has_place(meuang,khao_bandai_it_temple).
has_place(meuang,phra_ram_ratchaniwet).
has_place(meuang,chaosamran_beach).
has_place(cha_am,cha_am_beach).
has_place(cha_am,maruekhathaiyawan_palace).
has_place(cha_am,cha_am_forest_park).
has_place(cha_am,khao_nang_panthurat_forest_park).
has_place(cha_am,the_sirindhorn_international_environmental_park).
has_place(cha_am,somdet_phra_srinagarindra_park).
has_place(cha_am,neranchararam_temple).
has_place(cha_am,dok_krachiao_field).
has_place(cha_am,cha_am_khiri_temple).
has_place(cha_am,hoob_krapong_learning_center).
has_place(cha_am,huai_sai_education_development_center).
has_place(cha_am,thung_faek_valley).
has_place(cha_am,chao_por_khao_yai_shrine).
has_place(cha_am,tha_sai_island).
has_place(cha_am,na_yang_bat_cave).
has_place(cha_am,khao_ta_chin_cave).
has_place(cha_am,hup_sabu_waterfall).
has_place(cha_am,cha_am_atv_park).
has_place(cha_am,santorini_park).
has_place(cha_am,swiss_sheep_farm).
has_place(cha_am,camel_republic).
has_place(cha_am,the_venezia_huahin).
has_place(kaeng_krachan,kaeng_krachan_national_park).
has_place(khao_yoi,khao_yoi_cave).
has_place(khao_yoi,tai_dam_cultural_village).
has_place(ban_laem,ban_laem_salt_pan).
has_place(ban_laem,bang_tabun_bay).
has_place(ban_laem,khao_takrao_temple).
has_place(ban_laem,laem_luang_beach).
has_place(ban_laem,bang_khun_sai_village).
has_place(tha_yang,puek_tian_beach).
has_place(nong_ya_plong,nong_ya_plong_hot_springs).
is_type(phra_nakhon_khiri_historical_park,palace).
is_type(khao_luang_cave,cave).
is_type(khao_luang_cave,temple).
is_type(wat_khoi_temple,temple).
is_type(wat_yai_suwannaram_temple,temple).
is_type(saiyat_buddhist_temple,temple).
is_type(mahathat_worawihan_temple,temple).
is_type(kamphaeng_laeng_temple,temple).
is_type(khao_bandai_it_temple,cave).
is_type(khao_bandai_it_temple,temple).
is_type(phra_ram_ratchaniwet,palace).
is_type(chaosamran_beach,bay_and_beach).
is_type(cha_am_beach,bay_and_beach).
is_type(maruekhathaiyawan_palace,palace).
is_type(cha_am_forest_park,park).
is_type(khao_nang_panthurat_forest_park,park).
is_type(the_sirindhorn_international_environmental_park,park).
is_type(somdet_phra_srinagarindra_park,study_center).
is_type(neranchararam_temple,temple).
is_type(dok_krachiao_field,field).
is_type(cha_am_khiri_temple,cave).
is_type(hoob_krapong_learning_center,study_center).
is_type(hoob_krapong_learning_center,farm).
is_type(huai_sai_education_development_center,study_center).
is_type(thung_faek_valley,mountain).
is_type(chao_por_khao_yai_shrine,temple).
is_type(tha_sai_island,island).
is_type(tha_sai_island,mangrove_forest).
is_type(na_yang_bat_cave,cave).
is_type(khao_ta_chin_cave,cave).
is_type(hup_sabu_waterfall,waterfall).
is_type(cha_am_atv_park,theme_park).
is_type(santorini_park,theme_park).
is_type(santorini_park,water_park).
is_type(santorini_park,shops).
is_type(santorini_park,restaurants).
is_type(swiss_sheep_farm,farm).
is_type(camel_republic,theme_park).
is_type(camel_republic,zoo).
is_type(huai_sai_education_development_center,study_center).
is_type(the_venezia_huahin,theme_park).
is_type(the_venezia_huahin,shops).
is_type(the_venezia_huahin,zoo).
is_type(the_venezia_huahin,gallery).
is_type(the_venezia_huahin,restaurants).
is_type(kaeng_krachan_national_park,park).
is_type(kaeng_krachan_national_park,waterfall).
is_type(kaeng_krachan_national_park,mountain).
is_type(khao_yoi_cave,cave).
is_type(tai_dam_cultural_village,village).
is_type(ban_laem_salt_pan,salt_pan).
is_type(bang_tabun_bay,river).
is_type(bang_tabun_bay,mangrove_forest).
is_type(bang_tabun_bay,shops).
is_type(bang_tabun_bay,restaurants).
is_type(khao_takrao_temple,temple).
is_type(laem_luang_beach,bay_and_beach).
is_type(bang_khun_sai_village,village).
is_type(bang_khun_sai_village,mangrove_forest).
is_type(puek_tian_beach,bay_and_beach).
is_type(nong_ya_plong_hot_springs,hot_spring).
has_act(phra_nakhon_khiri_historical_park,visiting).
has_act(khao_luang_cave,religious_act).
has_act(khao_luang_cave,natural_observation).
has_act(wat_khoi_temple,religious_act).
has_act(wat_yai_suwannaram_temple,religious_act).
has_act(saiyat_buddhist_temple,religious_act).
has_act(mahathat_worawihan_temple,religious_act).
has_act(kamphaeng_laeng_temple,religious_act).
has_act(khao_bandai_it_temple,religious_act).
has_act(khao_bandai_it_temple,natural_observation).
has_act(phra_ram_ratchaniwet,visiting).
has_act(chaosamran_beach,seaside_act).
has_act(cha_am_beach,seaside_act).
has_act(maruekhathaiyawan_palace,visiting).
has_act(cha_am_forest_park,natural_observation).
has_act(cha_am_forest_park,camping).
has_act(khao_nang_panthurat_forest_park,natural_observation).
has_act(khao_nang_panthurat_forest_park,camping).
has_act(the_sirindhorn_international_environmental_park,natural_observation).
has_act(somdet_phra_srinagarindra_park,studying_culture).
has_act(neranchararam_temple,religious_act).
has_act(dok_krachiao_field,natural_observation).
has_act(cha_am_khiri_temple,natural_observation).
has_act(hoob_krapong_learning_center,studying_culture).
has_act(hoob_krapong_learning_center,natural_observation).
has_act(huai_sai_education_development_center,studying_culture).
has_act(thung_faek_valley,natural_observation).
has_act(thung_faek_valley,hiking).
has_act(chao_por_khao_yai_shrine,religious_act).
has_act(tha_sai_island,natural_observation).
has_act(tha_sai_island,growing_mangroves).
has_act(na_yang_bat_cave,natural_observation).
has_act(khao_ta_chin_cave,natural_observation).
has_act(hup_sabu_waterfall,swimming).
has_act(hup_sabu_waterfall,natural_observation).
has_act(cha_am_atv_park,playing).
has_act(santorini_park,eating).
has_act(santorini_park,playing).
has_act(santorini_park,visiting).
has_act(santorini_park,shopping).
has_act(santorini_park,swimming).
has_act(swiss_sheep_farm,playing).
has_act(swiss_sheep_farm,natural_observation).
has_act(camel_republic,playing).
has_act(camel_republic,visiting).
has_act(the_venezia_huahin,eating).
has_act(the_venezia_huahin,playing).
has_act(the_venezia_huahin,visiting).
has_act(the_venezia_huahin,shopping).
has_act(kaeng_krachan_national_park,hiking).
has_act(kaeng_krachan_national_park,natural_observation).
has_act(kaeng_krachan_national_park,camping).
has_act(kaeng_krachan_national_park,swimming).
has_act(khao_yoi_cave,natural_observation).
has_act(tai_dam_cultural_village,studying_culture).
has_act(ban_laem_salt_pan,natural_observation).
has_act(ban_laem_salt_pan,studying_culture).
has_act(bang_tabun_bay,natural_observation).
has_act(bang_tabun_bay,growing_mangroves).
has_act(bang_tabun_bay,sailing).
has_act(bang_tabun_bay,whale_watching).
has_act(bang_tabun_bay,eating).
has_act(bang_tabun_bay,shopping).
has_act(khao_takrao_temple,religious_act).
has_act(laem_luang_beach,seaside_act).
has_act(bang_khun_sai_village,studying_culture).
has_act(bang_khun_sai_village,growing_mangroves).
has_act(puek_tian_beach,seaside_act).
has_act(nong_ya_plong_hot_springs,natural_observation).
has_act(nong_ya_plong_hot_springs,bath_spa).
