:- module(facts,[]).

place(wat_yai_suwannaram_temple).
place(wat_khoi_temple).
place(thung_faek_valley).
place(the_venezia_huahin).
place(the_sirindhorn_international_environmental_park).
place(tha_sai_island).
place(tai_dam_cultural_village).
place(swiss_sheep_farm).
place(somdet_phra_srinagarindra_park).
place(santorini_park).
place(saiyat_buddhist_temple).
place(puek_tian_beach).
place(phra_ram_ratchaniwet).
place(phra_nakhon_khiri_historical_park).
place(nong_ya_plong_hot_springs).
place(neranchararam_temple).
place(na_yang_bat_cave).
place(maruekhathaiyawan_palace).
place(mahathat_worawihan_temple).
place(laem_luang_beach).
place(khao_yoi_cave).
place(khao_takrao_temple).
place(khao_ta_chin_cave).
place(khao_nang_panthurat_forest_park).
place(khao_luang_cave).
place(khao_bandai_it_temple).
place(kamphaeng_laeng_temple).
place(kaeng_krachan_national_park).
place(hup_sabu_waterfall).
place(huai_sai_education_development_center).
place(hoob_krapong_learning_center).
place(dok_krachiao_field).
place(chaosamran_beach).
place(chao_por_khao_yai_shrine).
place(cha_am_khiri_temple).
place(cha_am_forest_park).
place(cha_am_beach).
place(cha_am_atv_park).
place(camel_republic).
place(ban_laem_salt_pan).
place(bang_tabun_bay).
place(bang_khun_sai_village).
open_at(phra_nakhon_khiri_historical_park,9).
open_at(khao_luang_cave,9).
open_at(wat_khoi_temple,6).
open_at(wat_yai_suwannaram_temple,8).
open_at(saiyat_buddhist_temple,7).
open_at(mahathat_worawihan_temple,7).
open_at(kamphaeng_laeng_temple,7).
open_at(khao_bandai_it_temple,8).
open_at(phra_ram_ratchaniwet,8).
open_at(chaosamran_beach,0).
open_at(cha_am_beach,0).
open_at(maruekhathaiyawan_palace,9).
open_at(cha_am_forest_park,8).
open_at(khao_nang_panthurat_forest_park,9).
open_at(the_sirindhorn_international_environmental_park,9).
open_at(somdet_phra_srinagarindra_park,8).
open_at(neranchararam_temple,8).
open_at(dok_krachiao_field,9).
open_at(cha_am_khiri_temple,8).
open_at(hoob_krapong_learning_center,9).
open_at(thung_faek_valley,0).
open_at(chao_por_khao_yai_shrine,8).
open_at(tha_sai_island,8).
open_at(na_yang_bat_cave,8).
open_at(khao_ta_chin_cave,8).
open_at(hup_sabu_waterfall,8).
open_at(cha_am_atv_park,9).
open_at(santorini_park,10).
open_at(swiss_sheep_farm,9).
open_at(camel_republic,10).
open_at(huai_sai_education_development_center,8).
open_at(the_venezia_huahin,10).
open_at(kaeng_krachan_national_park,8).
open_at(khao_yoi_cave,7).
open_at(tai_dam_cultural_village,8).
open_at(ban_laem_salt_pan,8).
open_at(bang_tabun_bay,0).
open_at(khao_takrao_temple,8).
open_at(laem_luang_beach,0).
open_at(bang_khun_sai_village,8).
open_at(puek_tian_beach,0).
open_at(nong_ya_plong_hot_springs,8).
is_type(wat_yai_suwannaram_temple,temple).
is_type(wat_khoi_temple,temple).
is_type(thung_faek_valley,mountain).
is_type(the_venezia_huahin,zoo).
is_type(the_venezia_huahin,theme_park).
is_type(the_venezia_huahin,shops).
is_type(the_venezia_huahin,restaurants).
is_type(the_venezia_huahin,gallery).
is_type(the_sirindhorn_international_environmental_park,park).
is_type(tha_sai_island,mangrove_forest).
is_type(tha_sai_island,island).
is_type(tai_dam_cultural_village,village).
is_type(swiss_sheep_farm,farm).
is_type(somdet_phra_srinagarindra_park,study_center).
is_type(santorini_park,water_park).
is_type(santorini_park,theme_park).
is_type(santorini_park,shops).
is_type(santorini_park,restaurants).
is_type(saiyat_buddhist_temple,temple).
is_type(puek_tian_beach,bay_and_beach).
is_type(phra_ram_ratchaniwet,palace).
is_type(phra_nakhon_khiri_historical_park,palace).
is_type(nong_ya_plong_hot_springs,hot_spring).
is_type(neranchararam_temple,temple).
is_type(na_yang_bat_cave,cave).
is_type(maruekhathaiyawan_palace,palace).
is_type(mahathat_worawihan_temple,temple).
is_type(laem_luang_beach,bay_and_beach).
is_type(khao_yoi_cave,cave).
is_type(khao_takrao_temple,temple).
is_type(khao_ta_chin_cave,cave).
is_type(khao_nang_panthurat_forest_park,park).
is_type(khao_luang_cave,temple).
is_type(khao_luang_cave,cave).
is_type(khao_bandai_it_temple,temple).
is_type(khao_bandai_it_temple,cave).
is_type(kamphaeng_laeng_temple,temple).
is_type(kaeng_krachan_national_park,waterfall).
is_type(kaeng_krachan_national_park,park).
is_type(kaeng_krachan_national_park,mountain).
is_type(hup_sabu_waterfall,waterfall).
is_type(huai_sai_education_development_center,study_center).
is_type(huai_sai_education_development_center,study_center).
is_type(hoob_krapong_learning_center,study_center).
is_type(hoob_krapong_learning_center,farm).
is_type(dok_krachiao_field,field).
is_type(chaosamran_beach,bay_and_beach).
is_type(chao_por_khao_yai_shrine,temple).
is_type(cha_am_khiri_temple,cave).
is_type(cha_am_forest_park,park).
is_type(cha_am_beach,bay_and_beach).
is_type(cha_am_atv_park,theme_park).
is_type(camel_republic,zoo).
is_type(camel_republic,theme_park).
is_type(ban_laem_salt_pan,salt_pan).
is_type(bang_tabun_bay,shops).
is_type(bang_tabun_bay,river).
is_type(bang_tabun_bay,restaurants).
is_type(bang_tabun_bay,mangrove_forest).
is_type(bang_khun_sai_village,village).
is_type(bang_khun_sai_village,mangrove_forest).
has_place(tha_yang,puek_tian_beach).
has_place(nong_ya_plong,nong_ya_plong_hot_springs).
has_place(meuang,wat_yai_suwannaram_temple).
has_place(meuang,wat_khoi_temple).
has_place(meuang,saiyat_buddhist_temple).
has_place(meuang,phra_ram_ratchaniwet).
has_place(meuang,phra_nakhon_khiri_historical_park).
has_place(meuang,mahathat_worawihan_temple).
has_place(meuang,khao_luang_cave).
has_place(meuang,khao_bandai_it_temple).
has_place(meuang,kamphaeng_laeng_temple).
has_place(meuang,chaosamran_beach).
has_place(khao_yoi,tai_dam_cultural_village).
has_place(khao_yoi,khao_yoi_cave).
has_place(kaeng_krachan,kaeng_krachan_national_park).
has_place(cha_am,thung_faek_valley).
has_place(cha_am,the_venezia_huahin).
has_place(cha_am,the_sirindhorn_international_environmental_park).
has_place(cha_am,tha_sai_island).
has_place(cha_am,swiss_sheep_farm).
has_place(cha_am,somdet_phra_srinagarindra_park).
has_place(cha_am,santorini_park).
has_place(cha_am,neranchararam_temple).
has_place(cha_am,na_yang_bat_cave).
has_place(cha_am,maruekhathaiyawan_palace).
has_place(cha_am,khao_ta_chin_cave).
has_place(cha_am,khao_nang_panthurat_forest_park).
has_place(cha_am,hup_sabu_waterfall).
has_place(cha_am,huai_sai_education_development_center).
has_place(cha_am,hoob_krapong_learning_center).
has_place(cha_am,dok_krachiao_field).
has_place(cha_am,chao_por_khao_yai_shrine).
has_place(cha_am,cha_am_khiri_temple).
has_place(cha_am,cha_am_forest_park).
has_place(cha_am,cha_am_beach).
has_place(cha_am,cha_am_atv_park).
has_place(cha_am,camel_republic).
has_place(ban_laem,laem_luang_beach).
has_place(ban_laem,khao_takrao_temple).
has_place(ban_laem,ban_laem_salt_pan).
has_place(ban_laem,bang_tabun_bay).
has_place(ban_laem,bang_khun_sai_village).
has_act(wat_yai_suwannaram_temple,religious_act).
has_act(wat_khoi_temple,religious_act).
has_act(thung_faek_valley,natural_observation).
has_act(thung_faek_valley,hiking).
has_act(the_venezia_huahin,visiting).
has_act(the_venezia_huahin,shopping).
has_act(the_venezia_huahin,playing).
has_act(the_venezia_huahin,eating).
has_act(the_sirindhorn_international_environmental_park,natural_observation).
has_act(tha_sai_island,natural_observation).
has_act(tha_sai_island,growing_mangroves).
has_act(tai_dam_cultural_village,studying_culture).
has_act(swiss_sheep_farm,playing).
has_act(swiss_sheep_farm,natural_observation).
has_act(somdet_phra_srinagarindra_park,studying_culture).
has_act(santorini_park,visiting).
has_act(santorini_park,swimming).
has_act(santorini_park,shopping).
has_act(santorini_park,playing).
has_act(santorini_park,eating).
has_act(saiyat_buddhist_temple,religious_act).
has_act(puek_tian_beach,swimming).
has_act(puek_tian_beach,seaside_act).
has_act(phra_ram_ratchaniwet,visiting).
has_act(phra_nakhon_khiri_historical_park,visiting).
has_act(nong_ya_plong_hot_springs,natural_observation).
has_act(nong_ya_plong_hot_springs,bath_spa).
has_act(neranchararam_temple,religious_act).
has_act(na_yang_bat_cave,natural_observation).
has_act(maruekhathaiyawan_palace,visiting).
has_act(mahathat_worawihan_temple,religious_act).
has_act(laem_luang_beach,swimming).
has_act(laem_luang_beach,seaside_act).
has_act(khao_yoi_cave,natural_observation).
has_act(khao_takrao_temple,religious_act).
has_act(khao_ta_chin_cave,natural_observation).
has_act(khao_nang_panthurat_forest_park,natural_observation).
has_act(khao_nang_panthurat_forest_park,camping).
has_act(khao_luang_cave,religious_act).
has_act(khao_luang_cave,natural_observation).
has_act(khao_bandai_it_temple,religious_act).
has_act(khao_bandai_it_temple,natural_observation).
has_act(kamphaeng_laeng_temple,religious_act).
has_act(kaeng_krachan_national_park,swimming).
has_act(kaeng_krachan_national_park,natural_observation).
has_act(kaeng_krachan_national_park,hiking).
has_act(kaeng_krachan_national_park,camping).
has_act(hup_sabu_waterfall,swimming).
has_act(hup_sabu_waterfall,natural_observation).
has_act(huai_sai_education_development_center,studying_culture).
has_act(hoob_krapong_learning_center,studying_culture).
has_act(hoob_krapong_learning_center,natural_observation).
has_act(dok_krachiao_field,natural_observation).
has_act(chaosamran_beach,swimming).
has_act(chaosamran_beach,seaside_act).
has_act(chao_por_khao_yai_shrine,religious_act).
has_act(cha_am_khiri_temple,natural_observation).
has_act(cha_am_forest_park,natural_observation).
has_act(cha_am_forest_park,camping).
has_act(cha_am_beach,swimming).
has_act(cha_am_beach,seaside_act).
has_act(cha_am_atv_park,playing).
has_act(camel_republic,visiting).
has_act(camel_republic,playing).
has_act(ban_laem_salt_pan,studying_culture).
has_act(ban_laem_salt_pan,natural_observation).
has_act(bang_tabun_bay,whale_watching).
has_act(bang_tabun_bay,shopping).
has_act(bang_tabun_bay,sailing).
has_act(bang_tabun_bay,natural_observation).
has_act(bang_tabun_bay,growing_mangroves).
has_act(bang_tabun_bay,eating).
has_act(bang_khun_sai_village,studying_culture).
has_act(bang_khun_sai_village,growing_mangroves).
entrance_fee(phra_nakhon_khiri_historical_park,40).
entrance_fee(khao_luang_cave,20).
entrance_fee(wat_khoi_temple,20).
entrance_fee(wat_yai_suwannaram_temple,20).
entrance_fee(saiyat_buddhist_temple,20).
entrance_fee(mahathat_worawihan_temple,20).
entrance_fee(kamphaeng_laeng_temple,20).
entrance_fee(khao_bandai_it_temple,20).
entrance_fee(phra_ram_ratchaniwet,50).
entrance_fee(chaosamran_beach,0).
entrance_fee(cha_am_beach,0).
entrance_fee(maruekhathaiyawan_palace,30).
entrance_fee(cha_am_forest_park,50).
entrance_fee(khao_nang_panthurat_forest_park,50).
entrance_fee(the_sirindhorn_international_environmental_park,50).
entrance_fee(somdet_phra_srinagarindra_park,50).
entrance_fee(neranchararam_temple,20).
entrance_fee(dok_krachiao_field,0).
entrance_fee(cha_am_khiri_temple,20).
entrance_fee(hoob_krapong_learning_center,0).
entrance_fee(huai_sai_education_development_center,0).
entrance_fee(thung_faek_valley,0).
entrance_fee(chao_por_khao_yai_shrine,0).
entrance_fee(tha_sai_island,50).
entrance_fee(na_yang_bat_cave,50).
entrance_fee(khao_ta_chin_cave,50).
entrance_fee(hup_sabu_waterfall,20).
entrance_fee(cha_am_atv_park,100).
entrance_fee(santorini_park,50).
entrance_fee(swiss_sheep_farm,50).
entrance_fee(camel_republic,200).
entrance_fee(the_venezia_huahin,50).
entrance_fee(kaeng_krachan_national_park,300).
entrance_fee(khao_yoi_cave,50).
entrance_fee(tai_dam_cultural_village,0).
entrance_fee(ban_laem_salt_pan,0).
entrance_fee(bang_tabun_bay,0).
entrance_fee(khao_takrao_temple,20).
entrance_fee(laem_luang_beach,0).
entrance_fee(bang_khun_sai_village,0).
entrance_fee(puek_tian_beach,0).
entrance_fee(nong_ya_plong_hot_springs,20).
close_at(phra_nakhon_khiri_historical_park,17).
close_at(khao_luang_cave,16).
close_at(wat_khoi_temple,18).
close_at(wat_yai_suwannaram_temple,17).
close_at(saiyat_buddhist_temple,17).
close_at(mahathat_worawihan_temple,18).
close_at(kamphaeng_laeng_temple,17).
close_at(khao_bandai_it_temple,17).
close_at(phra_ram_ratchaniwet,16).
close_at(chaosamran_beach,24).
close_at(cha_am_beach,24).
close_at(maruekhathaiyawan_palace,16).
close_at(cha_am_forest_park,18).
close_at(khao_nang_panthurat_forest_park,16).
close_at(the_sirindhorn_international_environmental_park,16).
close_at(somdet_phra_srinagarindra_park,17).
close_at(neranchararam_temple,17).
close_at(dok_krachiao_field,16).
close_at(cha_am_khiri_temple,17).
close_at(hoob_krapong_learning_center,15).
close_at(thung_faek_valley,24).
close_at(chao_por_khao_yai_shrine,17).
close_at(tha_sai_island,17).
close_at(na_yang_bat_cave,17).
close_at(khao_ta_chin_cave,17).
close_at(hup_sabu_waterfall,17).
close_at(cha_am_atv_park,17).
close_at(santorini_park,21).
close_at(swiss_sheep_farm,18).
close_at(camel_republic,18).
close_at(huai_sai_education_development_center,16).
close_at(the_venezia_huahin,20).
close_at(kaeng_krachan_national_park,18).
close_at(khao_yoi_cave,17).
close_at(tai_dam_cultural_village,17).
close_at(ban_laem_salt_pan,17).
close_at(bang_tabun_bay,24).
close_at(khao_takrao_temple,17).
close_at(laem_luang_beach,24).
close_at(bang_khun_sai_village,17).
close_at(puek_tian_beach,24).
close_at(nong_ya_plong_hot_springs,17).
budget(phra_nakhon_khiri_historical_park,100).
budget(khao_luang_cave,80).
budget(wat_khoi_temple,20).
budget(wat_yai_suwannaram_temple,20).
budget(saiyat_buddhist_temple,20).
budget(mahathat_worawihan_temple,20).
budget(kamphaeng_laeng_temple,20).
budget(khao_bandai_it_temple,80).
budget(phra_ram_ratchaniwet,100).
budget(chaosamran_beach,300).
budget(cha_am_beach,300).
budget(maruekhathaiyawan_palace,100).
budget(cha_am_forest_park,500).
budget(khao_nang_panthurat_forest_park,500).
budget(the_sirindhorn_international_environmental_park,100).
budget(somdet_phra_srinagarindra_park,80).
budget(neranchararam_temple,20).
budget(dok_krachiao_field,100).
budget(cha_am_khiri_temple,20).
budget(hoob_krapong_learning_center,50).
budget(huai_sai_education_development_center,50).
budget(thung_faek_valley,50).
budget(chao_por_khao_yai_shrine,50).
budget(tha_sai_island,200).
budget(na_yang_bat_cave,100).
budget(khao_ta_chin_cave,100).
budget(hup_sabu_waterfall,150).
budget(cha_am_atv_park,500).
budget(santorini_park,500).
budget(swiss_sheep_farm,500).
budget(camel_republic,500).
budget(the_venezia_huahin,500).
budget(kaeng_krachan_national_park,1000).
budget(khao_yoi_cave,100).
budget(tai_dam_cultural_village,200).
budget(ban_laem_salt_pan,100).
budget(bang_tabun_bay,100).
budget(khao_takrao_temple,100).
budget(laem_luang_beach,100).
budget(bang_khun_sai_village,200).
budget(puek_tian_beach,100).
budget(nong_ya_plong_hot_springs,100).
activity(whale_watching).
activity(visiting).
activity(swimming).
activity(studying_culture).
activity(shopping).
activity(seaside_act).
activity(sailing).
activity(religious_act).
activity(playing).
activity(natural_observation).
activity(hiking).
activity(growing_mangroves).
activity(eating).
activity(camping).
activity(bath_spa).
act_age_range_start(whale_watching,5).
act_age_range_start(visiting,0).
act_age_range_start(swimming,5).
act_age_range_start(studying_culture,8).
act_age_range_start(shopping,0).
act_age_range_start(seaside_act,0).
act_age_range_start(sailing,5).
act_age_range_start(religious_act,0).
act_age_range_start(playing,10).
act_age_range_start(natural_observation,5).
act_age_range_start(hiking,15).
act_age_range_start(growing_mangroves,8).
act_age_range_start(eating,0).
act_age_range_start(camping,5).
act_age_range_start(bath_spa,5).
act_age_range_end(whale_watching,70).
act_age_range_end(visiting,200).
act_age_range_end(swimming,70).
act_age_range_end(studying_culture,200).
act_age_range_end(shopping,200).
act_age_range_end(seaside_act,200).
act_age_range_end(sailing,70).
act_age_range_end(religious_act,200).
act_age_range_end(playing,60).
act_age_range_end(natural_observation,200).
act_age_range_end(hiking,50).
act_age_range_end(growing_mangroves,60).
act_age_range_end(eating,200).
act_age_range_end(camping,70).
act_age_range_end(bath_spa,200).
